# Álgebra

<h2>1. Revisão de Álgebra Linear</h2>

<h3>1.1. Vetores</h3>

O **espaço euclidiano** $\mathbb R^n$ é o conjunto de todos os vetores de $n$ componentes. Se $\def\vect{\boldsymbol}\vect x \in \mathbb R^n$, então
$$
\vect x = \begin{pmatrix}x_1\\x_2\\\vdots\\x_n\end{pmatrix}.
$$

Vetores podem ser somados ou escalados. Sejam $\vect x, \vect y \in \mathbb R^n$ e $\alpha, \beta \in \mathbb R$, então
$$
\alpha\vect x + \beta\vect y = \alpha\begin{pmatrix}
x_1\\x_2\\\vdots\\x_n
\end{pmatrix} + \beta\begin{pmatrix}
y_1\\y_2\\\vdots\\y_n
\end{pmatrix} = \begin{pmatrix}
\alpha x_1 + \beta y_1\\\alpha x_2 + \beta y_2\\\vdots\\\alpha x_n + \beta y_n
\end{pmatrix}.
$$

<h3>1.2. Matrizes</h3>

Uma matriz pode ser descrita como um conjunto bidimensional de números reais dispotos em forma de tabela. Uma matriz $A$ de $m$ linhas por $n$ colunas (ou seja $A \in \mathbb R^{m \times n}$), é comumente escrita sob a forma
$$
A = \begin{pmatrix}%
    a_{1, 1} & a_{1, 2} & \dots  & a_{1, n}\\
    a_{2, 1} & a_{2, 2} & \dots  & a_{2, n}\\
    \vdots   & \vdots   & \ddots & \vdots\\
    a_{m, 1} & a_{m, 2} & \dots  & a_{m, n}
\end{pmatrix}.
$$

- Uma matriz pode ser pensada como uma coleção de colunas ou como uma coleção de linhas e ambas as interpretações podem ser úteis


- Um vetor $\vect x \in \mathbb R^n$ é considerado uma matriz com uma coluna e $n$ linhas

- Cada coluna de uma matriz $A \in \mathbb R^{m \times n}$ é um vetor $\vect a_j \in \mathbb R^m$, ou seja,
$$
\vect a_j = \begin{pmatrix}a_{1, j}\\a_{2, j}\\\vdots\\a_{m, j}\end{pmatrix}\quad\text e\quad A = \begin{pmatrix} \vect a_1 & \vect a_2 & \cdots & \vect a_n \end{pmatrix}.
$$

<h3>1.3. Produto Matriz-Vetor</h3>

Muito importante é a interpretação de uma matriz como um operador linear agindo em um espaço euclidiano através da operação do produto matriz-vetor.

Sejam $A \in \mathbb R^{m \times n}$ e $\vect x \in \mathbb R^n$, então podemos definir o produto matriz-vetor da seguinte forma:
$$
A\vect x = \begin{pmatrix}%
    a_{1, 1} & a_{1, 2} & \dots  & a_{1, n}\\
    a_{2, 1} & a_{2, 2} & \dots  & a_{2, n}\\
    \vdots   & \vdots   & \ddots & \vdots\\
    a_{m, 1} & a_{m, 2} & \dots  & a_{m, n}
\end{pmatrix}
\begin{pmatrix}
x_1\\x_2\\\vdots\\x_n
\end{pmatrix} =
\begin{pmatrix}
a_{1, 1}x_1 + a_{1, 2}x_2 + \cdots + a_{1, n}x_n\\
a_{2, 1}x_1 + a_{2, 2}x_2 + \cdots + a_{2, n}x_n\\
\vdots\\
a_{m, 1}x_1 + a_{m, 2}x_2 + \cdots + a_{m, n}x_n
\end{pmatrix}.
$$

Observe que
$$
A\vect x = x_1\vect a_1 + x_2\vect a_2 + \cdots + x_n \vect a_n.
$$
Ou seja, o produto matriz-vetor também pode ser interpretado como uma combinação linear das colunas de $A$.

<h3>1.4. Produto Matriz-Matriz</h3>

Sejam $A \in \mathbb R^{m \times q}$ e $B \in \mathbb R^{q \times n}$, então definimos o produto $AB$ entre $A$ e $B$ da seguinte forma:
$$\small
AB = \begin{pmatrix}
a_{1, 1}b_{1, 1} + a_{1, 2}b_{2, 1} + \cdots + a_{1, q}b_{q, 1} & a_{1, 1}b_{1, 2} + a_{1, 2}b_{2, 2} + \cdots + a_{1, q}b_{q, 2} & \cdots & a_{1, 1}b_{1, n} + a_{1, 2}b_{2, n} + \cdots + a_{1, q}b_{q, n}\\
a_{2, 1}b_{1, 1} + a_{2, 2}b_{2, 1} + \cdots + a_{2, q}b_{q, 1} & a_{2, 1}b_{1, 2} + a_{2, 2}b_{2, 2} + \cdots + a_{2, q}b_{q, 2} & \cdots & a_{2, 1}b_{1, n} + a_{2, 2}b_{2, n} + \cdots + a_{2, q}b_{q, n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m, 1}b_{1, 1} + a_{m, 2}b_{2, 1} + \cdots + a_{m, q}b_{q, 1} & a_{m, 1}b_{1, 2} + a_{m, 2}b_{2, 2} + \cdots + a_{m, q}b_{q, 2} & \cdots & a_{m, 1}b_{1, n} + a_{m, 2}b_{2, n} + \cdots + a_{m, q}b_{q, n}
\end{pmatrix}.
$$

Isto é equivalente a
$$
    AB = \begin{pmatrix} A\vect b_1 & A\vect b_2 & \cdots & A\vect b_n \end{pmatrix}
$$
e a
$$
(AB)_{i,j} = a_{i, 1}b_{1, j} + a_{i, 2}b_{2, j} + \cdots + a_{i, q}b_{q, j} = \sum_{k = 1}^qa_{i, k}b_{k, j}.
$$

<h3>1.5. Transposição</h3>

A operação de transposição "deita" a matriz, trocando linhas por colunas, ou seja, se
$$
A = \begin{pmatrix}%
    a_{1, 1} & a_{1, 2} & \dots  & a_{1, n}\\
    a_{2, 1} & a_{2, 2} & \dots  & a_{2, n}\\
    \vdots   & \vdots   & \ddots & \vdots\\
    a_{m, 1} & a_{m, 2} & \dots  & a_{m, n}
\end{pmatrix},
$$
então
$$
A^T = \begin{pmatrix}%
    a_{1, 1} & a_{2, 1} & \dots  & a_{m, 1}\\
    a_{1, 2} & a_{2, 2} & \dots  & a_{m, 2}\\
    \vdots   & \vdots   & \ddots & \vdots\\
    a_{1, n} & a_{2, n} & \dots  & a_{m, n}
\end{pmatrix}.
$$

Se $\vect c \in \mathbb R^n$, então
$$
 \vect c^T = \begin{pmatrix} c_1 & c_2 & \cdots & c_n \end{pmatrix}.
$$
Ou seja, se $\vect c, \vect x \in \mathbb R^n$, então
$$
    \vect c^T\vect x = c_1x_1 + c_2x_2 + \cdots + c_nx_n.
$$

- A transposta da soma é igual à soma das transpostas:
$$
(A + B)^T = A^T + B^T.
$$

- A transposta do produto é o produto das transposta na ordem inversa:
$$
(AB)^T = B^TA^T.
$$

In [ ]:
# Criação de matrizes:

import numpy as np

A = np.array(
    [
        [ 1, 2 ],
        [ 3, 4 ],
        [ 5, 6 ]
    ]
)

print('')
print(f'Print da matriz:\n {A}' )
print('')

print('Shape da matriz A:\n {}' .format(A.shape ))
print('')
# Criação de vetores:

x = np.array( [ 1, 1 ] )
print('')

print(f'print do vetor x: \n {x}' )
print('')

# Produto matriz-vetor:

print( f'produto matriz-vetor:\n {A @ x}' )
print('')

x = np.array( [ 1, 1 ] ).reshape( 2, 1 )
print( f'produto matriz-vetor deixando em pé:\n  {A @ x}' )
print('')








Print da matriz:
 [[1 2]
 [3 4]
 [5 6]]

Shape da matriz A:
 (3, 2)


print do vetor x: 
 [1 1]

produto matriz-vetor:
 [ 3  7 11]

produto matriz-vetor deixando em pé:
  [[ 3]
 [ 7]
 [11]]



In [ ]:
# Produto matriz-matriz

B = np.ones( ( 2, 4 ) )

print( f'print da matriz B: \n {B}' )
print('')

print(f'Produto matriz-matriz:\n  {A @ B}')
print('')

# Transposição de matrizes:
print( f'Produto interno e fazer tranposta ( A @ B ).T: \n {( A @ B ).T}' )
print('')
print( 'É igual a transposta B.T @ A.T: \n {}'.format( B.T @ A.T ) )
print('')

# Transposição de matrizes com numpy:
print( 'Transposta A em numpy:\n {}'.format(np.transpose( A )) )
print('')

print da matriz B: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Produto matriz-matriz:
  [[ 3.  3.  3.  3.]
 [ 7.  7.  7.  7.]
 [11. 11. 11. 11.]]

Produto interno e fazer tranposta ( A @ B ).T: 
 [[ 3.  7. 11.]
 [ 3.  7. 11.]
 [ 3.  7. 11.]
 [ 3.  7. 11.]]

É igual a transposta B.T @ A.T: 
 [[ 3.  7. 11.]
 [ 3.  7. 11.]
 [ 3.  7. 11.]
 [ 3.  7. 11.]]

Transposta A em numpy:
 [[1 3 5]
 [2 4 6]]

